### ISSUE TITLE
Настройка NOTIFY_USER_WANT_MESSAGE_CHECK не ограничивает создание уведомлений и их отправку

### ISSUE THREAD

**Issue by Folo4ka** [garpixcms/garpix_notify#35]
Результат функции указанной в настройке NOTIFY_USER_WANT_MESSAGE_CHECK (переменная user_want_message_check) используется в данном месте: https://github.com/garpixcms/garpix_notify/blob/master/backend/garpix_notify/models/notify.py#L368

тк continue прерываает только текущего уровня цикл, а не все по вложености вверх, по итогу, ложный результат никак не мешает созданию объектов Notify, и как следствие системные уведомления по сигналу отправляются, и по селери_биту так же все отправляется. 

Если значение user_want_message_check == False, то не должен создаваться объект Notify вообще, и в таком случае уведомление не будет отправлено, что и подрузумевает настройка NOTIFY_USER_WANT_MESSAGE_CHECK

**Comment by Alshevsky** [comment]
Спасибо, учту в следущем обновлении

**Comment by griviala** [comment]
Исправлено в https://github.com/garpixcms/garpix_notify/pull/36
