### ISSUE TITLE
Ошибка проверки необходимости создавать уведомления

### ISSUE THREAD

**Issue by Folo4ka** [garpixcms/garpix_notify#43]
есть условие` if user_check is None:` https://github.com/garpixcms/garpix_notify/blob/master/backend/garpix_notify/models/notify.py#L187
во-первых, зачем сравнивать именно с None, функция подразумевает проверку отправлять юзеру уведмоление или нет, так что логичнее чтобы она возвращала True или False (сейчас приходится возращать True или None),

Сразу далее идет опять `return None` из-за чего происходит ВЫХОД из функции отправки уведомлений по всем шаблонам и соответсвенно прерывается цикл выше `for template in templates:`, если у нас есть к примеру 4 шаблона, и если фукнция проверки необходимости отправлять уведомления вернула None на 2м шаблоне, уведомления по 3му и 4му шаблону не создадутся  и не отправятся.

Нужно вместо `return None` писать `continue`

**Comment by Folo4ka** [comment]
что думаете?

**Comment by Alshevsky** [comment]
@Folo4ka Поправлю, в след обновлении

**Comment by Folo4ka** [comment]
@Alshevsky когда планируете фикс в мастер мержить?

**Comment by Alshevsky** [comment]
@Folo4ka Да вообще должны уже скоро смержить.

**Comment by Alshevsky** [comment]
@Folo4ka Фиксы смержили

**Comment by griviala** [comment]
Исправлено в https://github.com/garpixcms/garpix_notify/pull/45/
